import "./globals.css";
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import NextAuthSessionProvider from "./provider/sessionProvider";
import MuiThemeProvider from "./provider/themeProvider";

const inter = Public_Sans({ weight: ["900", "400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MuiThemeProvider>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
